### PR TITLE
fix : notification mention , modified regex

### LINKED ISSUE #1874: [Bug] Notifications for mentions do not work
**Describe the bug or issue you're encountering**

No notifications for mentions (in objects or comments) working

**What are the relevant steps to reproduce, including the version(s) of the relevant software?**

1. Create a task
2. Mention another user inside the task or with a comment on the task
3. No notification created

**What is the expected behavior?**

1. Create a task
2. Mention another user inside the task or with a comment on the task
3. Notification created for the mentioned user

### PR DESCRIPTION
**Pull request by manab-pr**
modified regex ,so that it allows the fields in any order.

closes #1874

### CODE REVIEW

**Review by golanglemonade — APPROVED** [review]

File: pkg/slateparser/slate_parser.go [hunk 1]
```diff
@@ -41,22 +36,36 @@ var (
...
-			displayName := match[3] // data-slate-value (user.DisplayName)
-
-			mentions[slateID] = Mention{
-				UserID:          userID,
-				UserDisplayName: displayName,
-				ObjectType:      objectType,
-				ObjectID:        objectID,
-				ObjectName:      objectName,
-			}
+		if len(match) < 2 {
```
Comment (golanglemonade) [inline pkg/slateparser/slate_parser.go]: We can nolint this since its pretty well explained why there need to be more than 2 parts 
```suggestion
		if len(match) < 2 { //nolint:mnd
```
